# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 01:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=10)),
                ('cupo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='cedula',
            field=models.CharField(default=datetime.datetime(2016, 7, 20, 1, 52, 47, 786358, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
